### PR TITLE
Labs page and individual Lab page integrated with Baserow

### PR DESCRIPTION
**Pull request by minhuyenhoang**
@xplosionmind Now, these pages are getting data from Baserow and display on the website. The translation is also implemented in them.

The current URL for each lab look like this: `scambi.org/labs/lab-id`. Thus, if a lab has `id` equals `1` then the URL will be `scambi.org/labs/1`. The reason for this is because some lab has really long name with special characters, ex: `Combattere le disuguaglianze attraverso l’informazione e l’educazione: l’attivismo on e off-line` or `Vado a mappare la Pigna su #OpenStreetMap`. Please let me know your opinion about this.

For the lab card:
Screen Shot 2022-07-27 at 1 08 40 PM

- I have added tags for languages (haven't changed it to show actual language and not code).
- Each lab should have a short description/summary. This long description should only be used in the individual Lab page.

For the individual Lab page:

This is the section about the lab. As you can see, the long description is there. I have seen a `video` for the lab, but not `image`.
Screen Shot 2022-07-27 at 1 14 58 PM

This is lab host section. For the lab `Nodi`, there wasn't any host yet, that's why it's empty. And I don't see any `image` for host, so I put a random pic.
Screen Shot 2022-07-27 at 1 17 42 PM

### CODE REVIEW

**Comment by minhuyenhoang** [comment]
@xplosionmind About the Similar Lab section, how would you define labs to be similar? Like offer the same language?

**Comment by xplosionmind** [comment]
> how would you define labs to be similar?

Dividing Labs into categories does not make much sense, since some would be alone.

I do not want to over-complicate things, but: rather than having “similar labs” section, wouldn’t it be possible to call the section “following labs”, displaying the labs that start within the 30 minutes after the lab finishes? It would be so cool!

Otherwise, it would be fine jut to have “Other Labs” displaying some random other Lab.

**Comment by minhuyenhoang** [comment]
> wouldn’t it be possible to call the section “following labs”, displaying the labs that start within the 30 minutes after the lab finishes? It would be so cool!

I can do that. The Baserow just need to have a field called `start_time`, and I can filter and display the ones `that start within the 30 minutes after the lab finishes`.

**Comment by xplosionmind** [comment]
Unfortunately, it is a bit more complex, that is why if it is too much work you can drop it. Each Lab has a `duration` in minutes, and the `start_time` won't be only one, but more than one! Labs repeat over time, but in different ways.

**Pull request merged**
