### PR TITLE
apply new privacy policy

### PR DESCRIPTION
**Pull request by ghost**
I replaced 2022&copy;Scambi in stead of Privacy Policy in the footer. Thank you,

### CODE REVIEW

**Comment by xplosionmind** [comment]
Please, let us use [Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)](https://creativecommons.org/licenses/by-sa/4.0) for **everything except images**.

**Comment by ghost** [comment]
> Please, let us use [Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)](https://creativecommons.org/licenses/by-sa/4.0) for **everything except images**.

Absolutely, When you decide which Creative Commons License you use, please let me know. I will replace it!

**Comment by xplosionmind** [comment]
> When you decide which Creative Commons License you use, please let me know. I will replace it!

We would like to use the license I linked, if possible.

Thanks a lot!

**Comment by ghost** [comment]
> [Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)](https://creativecommons.org/licenses/by-sa/4.0)
Screen Shot 2022-08-11 at 8 46 54 AM
Screen Shot 2022-08-11 at 8 47 23 AM
It seem that there are 2 designs, which are normal one and compact one. Let me know your preference.   Thanks!

**Comment by xplosionmind** [comment]
> It seem that there are 2 designs, which are normal one and compact one. Let me know your preference.

Actually, if possible, I would keep things as minimal as possible and remove the image altogether. I would also cite the license only in abbreviated form: CC BY-SA 4.0

**Pull request merged**
