### PR TITLE
Dropdown menu for Navbar

### PR DESCRIPTION
**Pull request by traciingu**
Toggle open/close with menu clicks and auto-close when you click outside the dropdown.

The component expects to receive `children` in the following format: 
[ { title: "Title of Dropdown item", href: "dropdown-link "} ]

### CODE REVIEW

**Comment by minhuyenhoang** [comment]
@traciingu I changed the <a> tag into a button because it makes more sense. And when you use TailwindCSS ```@layer``` rule, all of them needs to be in the same CSS file, so I moved the style into ```global.css```

**Comment by traciingu** [comment]
@minhuyen-github So I meant for the button in the navbar to open the dropdown menu when it was clicked but not navigate anywhere. The links in the dropdown menu each take you to a different page

**Comment by minhuyenhoang** [comment]
> @minhuyen-github So I meant for the button in the navbar to open the dropdown menu when it was clicked but not navigate anywhere. The links in the dropdown menu each take you to a different page

Yep I just realized your intention too lol. I changed it to a button cause it does the same thing and it won't navigate us anywhere.

**Comment by minhuyenhoang** [comment]
I also saw you were trying to blur the page if the dropdown is opened, but I didn't see any blurring. Do we need the blur effect?

**Comment by traciingu** [comment]
@minhuyen-github Oh yea the onBlur is called when you focus anywhere outside of the component. So if you click off of it or tab focus outside the dropdown, the menu closes

**Comment by minhuyenhoang** [comment]
Ohhhhh so that's what it's for! I thought it's for blurring the page. I will change the name into something like onClickOutside so it's more clear.

**Comment by traciingu** [comment]
Haha yeaa. I'm not sure if you can change the name though cause it's a React event unless you know a way (onBlur is pretty confusing)

**Comment by minhuyenhoang** [comment]
In case, you didn't see my edited comment 😅 when we use Tailwind ```@layer```, every thing needs to be in the same CSS file, so I will move the style into ```global.css```

**Comment by traciingu** [comment]
Oh! Yea definitely didn't know that - I'll keep that in mind, thank you!

**Comment by traciingu** [comment]
I actually didn't mean to add to the layers "bucket" in Tailwind, I thought I had to use @layers to apply any Tailwind. Is it okay to use @apply without @layers in files outside of `global.css`?

**Comment by minhuyenhoang** [comment]
Ah you can just use Tailwind straight inside the component. For example: let's say you have a ```<p>``` tag with a paragraph inside that tag, and you want the text to be red. Then simply use the class ```text-red-100```  in the ```<p>``` tag. 
Like this: 
```<p className='text-red-100'> blah blah blah </p>```.
Just like how you would if you were to use Bootstrap. If you want to know every class, then check out their doc: https://tailwindcss.com/docs/installation.

They have everything that you need. Flex, grid, border, color, padding, margin, etc. They even have CSS animation. 

I use ```@layer``` and ```@apply``` because there were many classes for the button and it will be really long and hard to read if I were to put everything on 1 line lol.
For your case, I don't think it's a lot so I will probably just put the style inside the ```className```. That way it's more optimized.

**Comment by traciingu** [comment]
Ahh okay, I was hoping it was convention to have a separate file with Tailwind but thank you for the details!

**Comment by minhuyenhoang** [comment]
I made some changes in the style cause you would use it on the nav bar.

**Pull request merged**
