### PR TITLE
Rion next branch

### PR DESCRIPTION
**Pull request by ghost**
I replaced long line CSS blobs to SVG blob. Thank you,

### CODE REVIEW

**Comment by traciingu** [comment]
This looks great! A few notes:
- There are a few repeating links in the footer (Donate, Volunteer, Join Team)
- For Donate, Sydney was able to get the link. She left a comment for me on ClickUp: https://app.clickup.com/t/2m3qej3?comment=902293425
- Volunteer can link to the Contact page for now
- The text for the Subscribe button isn't centered on smaller screens

These don't work on very small screens (Was checking 280px for the GalaxyFold dimensions), but I also feel it's not as important if it takes a bit of time to fix:
- Email input doesn't fit inside the blob
- The Attend button has too much padding

**Comment by traciingu** [comment]
The Subscribe component:
- Input placeholder currently says "input"
- Input text is white
- Subscribe button says "button"

On very small screens (Smaller than iPhoneSE screen):
- Can use padding (Possibly increase width)

**Comment by minhuyenhoang** [comment]
> The Subscribe component:
> 
> * Input placeholder currently says "input"
> * Input text is white
> * Subscribe button says "button"
> 
> On very small screens (Smaller than iPhoneSE screen):
> 
> * Can use padding (Possibly increase width)

The reason for this is because this branch doesn't have the translation file yet.

**Comment by minhuyenhoang** [comment]
I like the `useMedia` hook that you have created to solve the problem that you're having! Very smart! 🤩  Bravo 🙌

**Comment by traciingu** [comment]
@sawabe0912 I pulled from main to check - it looks good! I did miss two links in the Footer - the Labs link is missing an 's' and Join Team can link to the Contact page for now. Other than that, it's good to go

**Pull request merged**
