### PR TITLE
Make navigation bar sticky and overlap

### PR DESCRIPTION
**Pull request by minhuyenhoang**
The navigation bar will be sticky and overlap the Lab hero header.

### CODE REVIEW

**Comment by minhuyenhoang** [comment]
@traciingu I think for the dropdown button, we should get rid of the ring style. In my opinion, when you click the dropdown button, the text should change to purple and stay purple until we click a different one. What do you think?

**Comment by traciingu** [comment]
I was thinking we have the ring to make it accessible so when someone tabs over it, it highlights which button they're on. But I do like the text colour change when the dropdown is open

**Comment by minhuyenhoang** [comment]
Maybe we can make the text color also change when they hover over it?

**Comment by traciingu** [comment]
Okay sure, I'll try that in place of the ring highlight

**Pull request closed without merging**
