### PR TITLE
Teams Page checking.

### PR DESCRIPTION
**Pull request by minhuyenhoang**
- Team Members will definitely only show people with `socio` as their role. The role is there for easier debug, thus, it will be removed when we released the website.
- The `image` link for the team member is changed to `http://x.scambi.org/profile_pics/Name_Surname.jpg`.

### CODE REVIEW

**Comment by xplosionmind** [comment]
> Team Members will definitely only show people with `socio` as their role.

I am sorry I need to correct you: you should not only include `socio` (a.k.a. associate), but also `Presidente` (president) `Vice Presidente` (vice-president) and a few more roles.

Therefore, I believe it is easier to simply **filter out** `ex socio` (former member) and `socio simpatizzante` (inactive member)

I sent Sydney a detailed feedback message specifying this.

**Comment by minhuyenhoang** [comment]
@xplosionmind Yep I added the filter for this, but I'm having a problem. In the `pino` database, the teams are all in Italian, but I was using the English version of teams. It would be nice if you could translate them for me.

**Comment by minhuyenhoang** [comment]
> @xplosionmind Yep I added the filter for this, but I'm having a problem. In the `pino` database, the teams are all in Italian, but I was using the English version of teams. It would be nice if you could translate them for me.

Never mind, I got it figured out by using the Scambi's manual.

**Comment by xplosionmind** [comment]
Sorry I could not help you faster.

**Comment by minhuyenhoang** [comment]
> Sorry I could not help you faster.

Don't worry! I just remembered the `manuale`.

**Comment by minhuyenhoang** [comment]
One more thing is that I have added Markdown files for all teams, English and Italian. I will need you to put in the Italian translations, and check the wording for English as well.

Those files are under folder `teams`.

**Comment by minhuyenhoang** [comment]
Here is what I have done:
- I added the filter to make sure that we are only include members that are NOT `ex socio` AND `socio simpatizzante`. I still left the `role` on the card so we can all check. 
- Created Markdown files for Italian translation.
- The profile pics are also changed to get from `x.scambi.org`, but there are some members that don't have a pic yet. 

@xplosionmind What I need you to do:
- Added the Italian translations for each team in their respective Markdown file. For example, the Owl team file is `civette.it.md`. All teams files are under `teams` folder.
- If you have any logo for the team, please put the link into `image` in the Markdown file.

**Pull request merged**
