### PR TITLE
JSON files for translation

### PR DESCRIPTION
**Pull request by minhuyenhoang**
@xplosionmind Here are the JSON files for translation contents on static pages such as Homepage, About, Labs, Pinoli, Film Festivals, and FAQ. 

The `common.json` file consists of reusable elements such as `manifesto` cards, buttons, etc. The Italian translation should be inside the `it` folder in the `public`.

For the Team page, please create Markdown file for the Italian version. Each team has their own folder, and the file should be named as `team.it.md`. The metadata is provided in the English version.

### CODE REVIEW

**Comment by xplosionmind** [comment]
Wonderful! I will be modifying the copywriting by the end of the day. I see that tags are in HTML… may I ask you if Markdown is supported, though?

**Comment by minhuyenhoang** [comment]
> Wonderful! I will be modifying the copywriting by the end of the day. I see that tags are in HTML… may I ask you if Markdown is supported, though?

Which tags are you talking about? The tags on Lab card?

**Comment by xplosionmind** [comment]
> Which tags are you talking about?

I mean [HTML tags](https://developer.mozilla.org/en-US/docs/Glossary/Tag) in the strict sense of the term: `<strong>`, `<em>`, etc…

Instead of HTML, can I use Markdown?

**Comment by minhuyenhoang** [comment]
Ah yeah, go ahead! I used HTML tag cause some of the words have different colors.

**Comment by xplosionmind** [comment]
I added all of the translations that were there. Please, keep the PR open since I still have to review the English copywriting.

Thanks!

**Comment by minhuyenhoang** [comment]
No worries! I have a question, so I noticed that you used flag for the language switch on the navigation bar. Would you want the same thing for the English site?

**Comment by xplosionmind** [comment]
Ok, copywriting should be now ok! You can merge this branch.

**Comment by xplosionmind** [comment]
> No worries! I have a question, so I noticed that you used flag for the language switch on the navigation bar. Would you want the same thing for the English site?

Yes, thanks!

**Comment by minhuyenhoang** [comment]
@xplosionmind I noticed that you added in these links: 
```
/paneuretico
/oltre
```

Are they the Italian version for labs and teams? Like the Italian URL for those pages? 
If you want Italian for all pages URL then I will create a JSON file for it, and you can fill it out.

**Comment by minhuyenhoang** [comment]
I just found out I forgot to add a field for these:
Screen Shot 2022-08-10 at 6 03 37 PM
Screen Shot 2022-08-10 at 7 28 09 PM
Screen Shot 2022-08-10 at 7 28 25 PM


I just added it in the `common.json`, could you tell me the Italian for this? I can add it in myself.
And one more thing, I haven't add the JSON file for the Film Festival page. Let me add it real quick for you.

**Comment by xplosionmind** [comment]
> could you tell me the Italian for this?

- Support is today -> Sostienici, dona ora!
- Our Manifesto -> Il Manifesto
- Explore Scambi -> Mappa delle location

**Comment by xplosionmind** [comment]
> Are they the Italian version for labs and teams?

Nope. They are, respectively:
- the permalink to the blog article explaining the term “paneurethic” in Italian
- the link of a page to be created, with a few information about our association (named “Oltre”). Something close to what is currently in https://scambi.org/oltre
  **Note**: we can create this page in Markdown by ourselves with no problems, as soon as we have the functionality.

---

> If you want Italian for all pages URL then I will create a JSON file for it, and you can fill it out.

It would be super nice if we could choose arbitrary short permalinks for each page. In order not to break all previous links, though, it is critical that there is some kind of **redirection** from original or alternative URLs, as I wrote in the email I sent you (did you get it? If not, check the spam. I sent it from staff@scambi.org)

**Comment by minhuyenhoang** [comment]
> the link of s page to be created

Got a typo here so I don't know which page 😅

> It would be super nice if we could choose arbitrary short permalinks for each page. In order not to break all previous links, though, it is critical that there is some kind of **redirection** from original or alternative URLs, as I wrote in the email I sent you (did you get it? If not, check the spam. I sent it from [staff@scambi.org](mailto:staff@scambi.org))

Yep, I just checked the mail again and saw that email. Thank you for explaining that! It made more sense now. We can definitely do that. It's a piece of cake 🍰 with NextJS.

**Comment by xplosionmind** [comment]
> Got a typo here so I don't know which page 😅

I just fixed it. Sorry!

> Yep, I just checked the mail again and saw that email. Thank you for explaining that! It made more sense now. We can definitely do that. It's a piece of cake 🍰 with NextJS. 

That is great to know. Thanks!

**Comment by xplosionmind** [comment]
Just to be sure: do I need to do something else in order for this PR to be merged?

**Comment by minhuyenhoang** [comment]
> Just to be sure: do I need to do something else in order for this PR to be merged?

Yep, can you check my reviews? Cause I saw some of the JSON files were missing fields or translations.

**Comment by xplosionmind** [comment]
Thanks for pointing out I missed something, @minhuyenhoang!
Sorry if I did it again. Let me know!

Best,
T

**Comment by minhuyenhoang** [comment]
> Thanks for pointing out I missed something, @minhuyenhoang! Sorry if I did it again. Let me know!
> 
> Best, T

No worries! 😉 
I missed something too. I just created a file for the film festival page cause I forgot it earlier. Could you add the translation?
Thank you

**Pull request merged**
