### PR TITLE
Integrate Baserow for individual Team page

### PR DESCRIPTION
**Pull request by minhuyenhoang**
Remove the Markdown implementation for individual Team page, and integrate Baserow so the website will display the list of team members

@xplosionmind Just a few thing I would need from you:
- The team  member database doesn't have `image` and `bio`. So I just leave them empty for now.
- The teams are gonna be Markdown files so you can edit the content. Please make sure that the names are correct.
- Add the Italian version by creating another Markdown called `team-name.it.md` inside folder `team-name`. If a team has a different name in Italian, for example `Ciao` and `Hello` then the files will be `ciao.it.md` and `hello.en.md`.

### CODE REVIEW

**Comment by xplosionmind** [comment]
> The team  member database doesn't have `image` and `bio`. So I just leave them empty for now.

I am sorry I did not add those fields. In the [`Libro soci` table](https://baserow.io/database/22288/table/56862) you now have `bio`, `bio_en`, `profile_pic`. It will take some time to fill everything out, but by the beginning of the festival everything will be filled out.  
**NOTE**: please only display people whose `role` != `ex socio` && `role` != `socio simpatizzante`!

It would be great if, in the case `profile_pic` is empty, the URL of the profile image is defaulted to `https://x.scambi.org/profile_pics/Name_Surname.jpg` (note that `x.scambi.org` has not been set up, yet).

---

> Please make sure that the names are correct.

- no need for `steinbock-ibexes`: just `steinbocks` is ok!
- the only missing team is `silicon`

**Comment by minhuyenhoang** [comment]
Thank you so much! I will add those fields into the code. 
The `silicon` team is actually not on the Figma so I was wondering if you have the wording for it? 
Do you have the links to each team's logo/image? Or they don't have any logo/image?

**Comment by xplosionmind** [comment]
> Do you have the links to each team's logo/image? Or they don't have any logo/image?

Noooooooooooo! Just yesterday I created some nice custom images for each team’s Telegram group, but I am stupid and I did not keep the original file.

Actually, it was very simple because they just were vector images taken from the web and adapted to our palette.

Anyways, we might consider taking group pictures of each team during the festival this year, but let us skip team logo/image for now.

manuale.scambi.org is our bible and it is definitely updated. Be aware, though, that the English version might not be as up to date as the Italian one.

**Comment by minhuyenhoang** [comment]
I just realized that the wording of each team on Figma is totally different with the one in `manuale`. Which one do you want to use for the card and which one for the individual team page?

**Comment by xplosionmind** [comment]
Do not worry about wording, once most of the stuff is finalized, our writing team (the Snails) will do a 2h full-immersion and revise/rewrite all of the written parts.

The Manual version is for sure tue best, but we would be changing something anyways: the Manual is intended to be for ourselves, while the website is intended for the public!

**Comment by minhuyenhoang** [comment]
Okie! Awesome! So just to let you know that if they want to change the wording, then they can just change the Markdown file content.
Oh and I'm still waiting on your encrypted email.

**Comment by xplosionmind** [comment]
> Check the spam! I am sure I sent it…

I still haven't seen it in the inbox and spam :((

**Pull request merged**
